---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Reload crowdsec
  ansible.builtin.systemd:
    name: crowdsec
    state: reloaded
